### ISSUE TITLE
RAP Tools installation failed partially in Eclipse 2023-12 (4.30.0)

### ISSUE THREAD

**Issue by GiantCrocodile** [eclipse-rap/org.eclipse.rap.tools#66]
Hello,

when you try to isntall the RAP Tools according to https://eclipse.dev/rap/developers-guide/devguide.php?topic=setup-ide.html&version=3.27, you get an error with Eclipse 2023-12 (4.30.0):

![grafik](https://github.com/eclipse-rap/org.eclipse.rap.tools/assets/6271057/bd4da310-1319-4cd4-ac52-b511a24475bd)

Error text from screenshot:
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: RAP Tools 3.1.2.20170215-1811 (org.eclipse.rap.tools.feature.feature.group 3.1.2.20170215-1811)
  Missing requirement: Jetty :: XML utilities 9.3.9.v20160517 (org.eclipse.jetty.xml 9.3.9.v20160517) requires 'java.package; org.eclipse.jetty.util [9.3.9,9.3.10)' but it could not be found
  Cannot satisfy dependency:
    From: RAP Tools 3.1.2.20170215-1811 (org.eclipse.rap.tools.feature.feature.group 3.1.2.20170215-1811)
    To: org.eclipse.equinox.p2.iu; org.eclipse.jetty.xml [9.3.9.v20160517,9.3.9.v20160517]
```

You can still continue the setup and it looks like the tools do work afterwards but this error is not intended, I think.

Best Regards,

**Comment by ifurnadjiev** [comment]
Please use the latest RAP Tools 3.27 SR1 from our download page. You are trying to install a 7 years old (RAP Tools 3.1.2.20170215-1811 ) in the latest Eclipse IDE (Eclipse 2023-12 (4.30.0)).

**Comment by GiantCrocodile** [comment]
Worked like a charm, thanks for that. I didn't notice that the update URL provided in the tutorial wasn't up2date while I checked it just roughly . . . was related to https://github.com/eclipse-rap/org.eclipse.rap.website/issues/2
