### ISSUE TITLE
Launching RWT 4 standalone application in the eclipse IDE fails

### ISSUE THREAD

**Issue by Sebastian-Habenicht** [eclipse-rap/org.eclipse.rap.tools#93]
Launching RWT 4 standalone application in IDE (new eclipse 2024-09 installation, new java project, according to the RAP dev guide) fails with _"Servlet class org.eclipse.rap.rwt.engine.RWTServlet is not a javax.servlet.Servlet"_ I described my steps in more detail in the respective forum topic [1].
RWT Launcher was always working with 3.x, so I never though much about it and might have simply missed or misconfigured something to get it running with 4, but i cannot see what it might be. Please point me in the right direction in this case. 

However, I had a look at the tools project (main) and found that _JettyLauncher_ code is obviously still EE8 based, while it is said that RAP 4 requires Jakarta 6 and therefore EE10. I managed to launch RWT 4 application after some adjustments; 
- changed _JettyLauncher_  to use EE10 _WebAppContext_ (based on embedded jetty EE10 servlet container example [2])  instead of EE8
- adjusted required bundles in the manifest (EE10 instead of EE8 bundles, added _jakarta.servlet-api_ and _org.eclipse.jetty.ee_ bundles) and adjusted the class path list in _RWTLaunchDelegate_ accordingly

With these changes, the 'dev guide way' works with RWT 4 (to just add the RWT jar files to the class path, implement an _AbstractEntryPoint_ and run it via "Run as RWT Application"). Only minor difference to 3.x is that SLF4j implementation has to be provided for the logging.

For the changes made to the tools project, it was necessary to add these plugins to the target runtime (which was the Running Platform):
- org.eclipse.jetty.ee10.servlet (12.0.12)
- org.eclipse.jetty.ee10.webapp (12.0.12)

Does RWTLauncher needs to be adjusted for EE10 support (or an EE10 based launcher must be added to support both in the IDE) , or am I wrong?

[1] https://www.eclipse.org/forums/index.php?t=msg&th=1116339&goto=1872422&#msg_1872422
[2] https://github.com/jetty/jetty-examples/blob/12.0.x/embedded/ee10-servlet-server/src/main/java/examples/EmbedMe.java

**Comment by ifurnadjiev** [comment]
Could you please create a PR with your changes?

**Comment by Sebastian-Habenicht** [comment]
Thanks, I have already updated and can verify that my EE10 application now launches as expected. 
While I was looking into the tools project I have implemented Jakarta version selection for a launch configuration, see attached image. Not sure if EE8 should still be supported for RWT Launcher in Eclipse 2024-12 and higher; it might be helpful when people want to update their IDE, but cannot migrate their projects from RAP 3.x to 4 in the short or medium term. What do you think, would that selection option make sense?
![switch](https://github.com/user-attachments/assets/dc8d4a85-2a24-44ba-b72a-ccbdf983ebae)

**Comment by Sebastian-Habenicht** [comment]
Sure, I have created the PR, please have a look. I do not switch the target platform, as the required EE8 and EE10 jetty bundles will be provided with the IDE build, won't they? Tested with different target platforms (running the change in tools as an Eclipse Application), EE8 and EE10 apps can be launched with different target platforms selected (Running Platform, RAP3, RAP4).
